title: Balesevic Srdjan
logo: https://avatars.githubusercontent.com/u/37658865
email: srdjan.balesevic@hotmail.com
#description: text below image
#show_downloads: true
#theme: jekyll-theme-minimalistic
remote_theme: vaibhavvikas/jekyll-theme-minimalistic
color-scheme: light

webmaster_verifications:
  #bing: 6605C60582C09EBF05D19C7AA9FF5496
  bing: 78FE17549C9303A86665F2ECA50117F0
  google: HcgjQ9u13iaWAG1FyF9yFp6-f9QYrwstKoKPNrRbbqM
  #google: YXXACXsZjuu041kl41yKLww4xdiiudN1S0IEtdEeGSE

social:
  name: Baleshevich Srdjan
  links:
    - https://github.com/baleshsrle
    - https://www.goodreads.com/baleshsrle
    - https://www.linkedin.com/in/srdjanbaleshevich
    - https://baleshsrle.t.me
    - https://wa.me/38766340286

plugins:
 - jekyll-remote-theme
 - jekyll-seo-tag
 - jekyll-target-blank

platforms: 
  #- name: Discord
  #  icon: <i class="fa-brands fa-discord fa-xl"></i>
  #  link: https://discord.com/users/952891242574917652

  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin fa-xl"></i>
    link: https://ba.linkedin.com/in/srdjanbaleshevich
  
  - name: Messenger
    icon: <i class="fa-brands fa-facebook-messenger fa-xl"></i>
    link: https://m.me/srdjan.balesevic

  #- name: Signal
  #  icon: <i class="fa-brands fa-signal-messenger fa-xl"></i>
  #  link: skype:srdjan.baleshevich?call

  #- name: Skype
  #  icon: <i class="fa-brands fa-skype fa-xl"></i>
  #  link: skype:srdjan.baleshevich?call

  - name: Telegram
    icon: <i class="fa-brands fa-telegram fa-xl"></i>
    link: https://baleshsrle.t.me

  #- name: Viber
  #  icon: <i class="fa-brands fa-viber fa-xl"></i>
  #  link: https://conf.viber.com/vA2f9hXPPZJyXVW4Gw2YDQ

  - name: WhatsApp
    icon: <i class="fa-brands fa-whatsapp fa-xl"></i>
    link: https://wa.me/38766340286